type Category {
  _id: ID!
  label: String!
}

###################################

input CategoriesToAdd {
  label: String!
}

input AddCategoriesParams {
  returnAll: Boolean
  categoriesToAdd: [CategoriesToAdd!]
}

type AddCategoriesReturn {
  all: [Category!]
  addedData: [Category!]
}

###################################

input CategoryToUpdate {
  _id: ID!
  label: String!
}

input UpdateCategoriesParams {
  returnAll: Boolean
  categoriesToUpdate: [CategoryToUpdate!]
}

type UpdateCategoriesReturn {
  all: [Category!]
  updatedData: [Category!]
}

###################################

input DeleteCategoriesParams {
  returnAll: Boolean
  idsToDelete: [ID!]
}

type DeleteCategoriesReturn {
  all: [Category!]
  deletedData: [Category!]
}

###################################

type Query {
  categories: [Category!]!
}

type Mutation {
  addCategories(params: AddCategoriesParams): AddCategoriesReturn
  updateCategories(params: UpdateCategoriesParams): UpdateCategoriesReturn
  deleteCategories(params: DeleteCategoriesParams): DeleteCategoriesReturn
}
