type User {
  _id: ID!
  name: String!
  avatar: String!
}

###################################

input UserToAdd {
  name: String!
  avatar: String!
}

input AddUsersParams {
  returnAll: Boolean
  usersToAdd: [UserToAdd!]
}

type AddUsersReturn {
  all: [User!]
  addedData: [User!]
}

###################################

input UserToUpdate {
  _id: ID!
  name: String!
  avatar: String!
}

input UpdateUsersParams {
  returnAll: Boolean
  usersToUpdate: [UserToUpdate!]
}

type UpdateUsersReturn {
  all: [User!]
  updatedData: [User!]
}

###################################

input UserToDelete {
  _id: ID!
}

input DeleteUsersParams {
  returnAll: Boolean
  idsToDelete: [ID!]
}

type DeleteUsersReturn {
  all: [User!]
  deletedData: [User!]
}

###################################

type Query {
  users: [User]
}

type Mutation {
  addUsers(params: AddUsersParams): AddUsersReturn
  updateUsers(params: UpdateUsersParams): UpdateUsersReturn
  deleteUsers(params: DeleteUsersParams): DeleteUsersReturn
}
